= pg_stat_activity

Para comprobar la actividad actual en la base de datos, consultas en ejecución, bloquedas, conexiones concurrentes, ociosas (idle), etc.

== Estructura

* backend_start: Tiempo cuando se inicio la sesion.
* xact_start: Tiempo cuando se inicio la transaccion actual, NULL si no hay una transaccion actual.
* query_start: Tiempo cuando el query activo se inicio. Si `state != 'active'` indica cuando se inicio el ultimo query ejecutado por esta sesion.
* waiting: La backend session esta esperando por algo.
* state: Indicia el estado de la backend session.
** active: La backend session esta ejecutando un query.
** idle: La backend session esta esperando un nuevo comando.
** idle in transaction: La backend session esta en transaccion, pero no esta ejecutando un query.
** idle in transaction (aborted): Es similar a `idle in transaction`, pero uno de los statement causo un error.
** fastpath function call: La backend session esta ejecutando a `fast-path function`.
** disabled: Este estado es reportado si `track_activities` esta desactivado para esta backend session.
* query: Si `state = 'active'` muestra el query en ejecuccion, sino muestra el ultimo query ejecutado. El texto es truncado a 1024 caracteres.