= System Views

Some usefuls views used by our troubleshooting queries:

* https://www.postgresql.org/docs/9.6/monitoring-stats.html#PG-STAT-ACTIVITY-VIEW[pg_stat_activity]
** Show current activity
** The query column show the current or latest query and the length is limited by _track_activity_query_size_ (SHOW track_activity_query_size;). During startup memory is reserved for this _max_connections x track_activity_query_size_.
* https://www.postgresql.org/docs/9.6/monitoring-stats.html#PG-STAT-DATABASE-VIEW[pg_stat_database]
** Show stats from our DB.
** We can restart this stats using _pg_stat_reset()_.
* https://www.postgresql.org/docs/9.6/monitoring-stats.html#PG-STAT-BGWRITER-VIEW[pg_stat_bgwriter]
** Show details about _writer (Background Writer)_ and _checkpoint (Checkpointer)_ process.
** _writer (Background Writer)_ is a separate process which writes to disk _dirty buffers_, the idea is reduce the amount of work for the _checkpoint (Checkpointer)_. The column _buffers_clean_ shows the number of buffers cleaned by this process.
** _checkpoint (Checkpointer)_ is executed a regular intervals defined by _checkpoint_timeout_. Also this can be executed on demand when the max number of WAL files is reached.
** We can use _checkpoints_timed_ and _checkpoints_req_ which indicates timed execution vs on demand execution. A high value on _checkpoints_req_ could indicate a low size for WAL files. We can check WAL Max Size using _max_wal_size_.
* https://www.postgresql.org/docs/9.6/monitoring-stats.html#PG-STAT-SSL-VIEW[pg_stat_ssl]
** Show SSL information.
* https://www.postgresql.org/docs/9.6/view-pg-locks.html[pg_locks]
** We use the _mode_ column to understand the type of lock acquired by each backend process. We can use the https://www.postgresql.org/docs/9.6/explicit-locking.html[locking documentation] to understand more about this.