= Troubleshooting

Collection of multiples queries that may be useful when analyzing performance issues. This includes information about locks, index usage, buffer cache hit ratios , vacuum statistics, etc.

`*link:blocking.sql[blocking]*`
[options="nowrap"]
```
pid  | usename  |             query             | blocking_id |   blocking_state    |        blocking_query
-----+----------+-------------------------------+-------------+---------------------+-------------------------------
  38 | postgres | UPDATE numbers SET value = 5; |          39 | idle in transaction | UPDATE numbers SET value = 4;
(1 row)
```

This query displays statements that are currently holding locks that other statements are waiting to be released. This can be used in conjunction with `*locks*` to determine which statements need to be terminated in order to resolve lock contention.

*Note:* The column `blocking_query` could mean that the query is still running or that was the last query executed by the blocking pid. We need to check the column `blocking_state` to understand this, where _active_ means query still running.

`*link:locks.sql[locks]*`
[options="nowrap"]
```
pid  | relname | transactionid |         mode        | locktype | granted |         query_snippet         |       age
-----+---------+---------------+---------+---------+---------+-------------------------------+-----------------------------
  39 |         |         47203 | AccessExclusiveLock | tuple    | t       | UPDATE numbers SET value = 4; | 00:18:02.474137
  39 |         |               | AccessExclusiveLock | tuple    | t       | UPDATE numbers SET value = 4; | 00:18:02.474137
  38 | numbers |               | AccessExclusiveLock | tuple    | t       | UPDATE numbers SET value = 5; | 00:17:59.464137
  38 |         |         47204 | AccessExclusiveLock | tuple    | t       | UPDATE numbers SET value = 5; | 00:17:59.464137
  38 |         |               | AccessExclusiveLock | tuple    | t       | UPDATE numbers SET value = 5; | 00:17:59.464137
(5 rows)
```

This query displays queries that have taken out an exlusive lock on a relation. Exclusive locks typically prevent other operations on that relation from taking place, and can be a cause of "hung" queries that are waiting for a lock to be granted.

`*link:long-running-queries.sql[long-running-queries]*`
[options="nowrap"]
```
 pid |    duration     |             query             |        state
-----+-----------------+-------------------------------+---------------------
  39 | 00:33:13.750108 | UPDATE numbers SET value = 4; | idle in transaction
  38 | 00:33:10.259885 | UPDATE numbers SET value = 5; | active
(2 rows)
```

This query displays currently running queries, that have been running for longer than 5 seconds, descending by duration. Very long running queries can be a source of multiple issues, such as preventing DDL statements completing or vacuum being unable to update `relfrozenxid`.

*Note:* We can also use its variants to detect long running transactions and long running connections. It is important because maybe our DB is performing but we are using very long transactions which could generate some contention on the DB. Its variant about long running connections allows us to detect long live backend process which would be top contributors about memory usage due to its internal caching.

`*link:statements.sql[statements]*`
[options="nowrap"]
```
                   query_snippet                    |   calls    |    total_time    |      mean       | percentage_cpu | sync_io_time
----------------------------------------------------+------------+------------------+-----------------+----------------+--------------
 SELECT * FROM numbers                              | 2928907107 | 470:05:44.191507 | 00:00:00.000578 |          69.90 | 00:00:00
 SELECT * FROM vac                                  | 4514502866 | 49:08:01.929032  | 00:00:00.000039 |           7.31 | 00:00:00
(2 rows)
```

This query displays statements, obtained from `pg_stat_statements`, ordered by the amount of time to execute in aggregate. This includes the statement itself, the total execution time for that statement, the proportion of total execution time for all statements that statement has taken up, the number of times that statement has been called, and the amount of time that statement spent on synchronous I/O (reading/writing from the filesystem), sync_io_time only is available when _track_io_timing_ is enabled (Off by default).

*Note:* To use this query you have to configure the https://www.postgresql.org/docs/9.6/pgstatstatements.html[pg_stat_statements] extension.

`*link:buffers.sql[buffers]*`
[options="nowrap"]
```
     name     | type  | buffers |  buffered  | buffer_percentage | relation_percentage
--------------+-------+---------+------------+-------------------+---------------------
 film         | Table |      55 | 440 kB     |               0.3 |                91.7
(1 row)
```

This query displays the usage of shared_buffers database cache. The output ordered by relation percentage taken in shared buffer, it also shows that how much of the whole relation is buffered.

*Note:* To use this query you have to configure the https://www.postgresql.org/docs/9.6/pgbuffercache.html[pg_buffercache] extension.

`*link:duplicated-indexes.sql[duplicated-indexes]*`
[options="nowrap"]
```
    table     |     type      |                              indexes
--------------+---------------+-------------------------------------------------------------------
 vac          | Exact Match   | {vac_data,vac_data_duplicate}
 vac          | Partial Match | {vac_data,vac_data_duplicate,vac_data_multiple}
 pg_enum      | Partial Match | {pg_enum_typid_label_index,pg_enum_typid_sortorder_index}
 pg_attribute | Partial Match | {pg_attribute_relid_attnam_index,pg_attribute_relid_attnum_index}
(4 rows)
```

This query displays duplicated indexes using two strategies.

1. Exact Match: In this case the index is using the same columns in the same order, so duplicated indexes could be removed.

2. Partial Match: In this case the first component of the index is used in other index, we need to analyze if we can remove the other indexes. This can be used in conjunction with `*unused-indexes*`.

`*link:unused-indexes.sql[unused-indexes]*`
[options="nowrap"]
```
      table       |                index                | index_size | index_scans
------------------+-------------------------------------+------------+-------------
 rental           | idx_fk_inventory_id                 | 496 kB     |           0
 payment          | idx_fk_staff_id                     | 464 kB     |           25
 payment          | idx_fk_customer_id                  | 368 kB     |           1
(3 rows)
```

This query displays indexes that have < 50 scans recorded against them, and are greater than 5 pages in size, ordered by index size. It is generally useful for eliminating indexes that are unused, which can impact write performance, as well as read performance should they occupy space in memory.

`*link:index-usage.sql[index-usage]*`
[options="nowrap"]
```
  table   | usage_percentage | estime_rows
----------+------------------+-------------
 film     |               99 |        1000
 category |               99 |          16
 language |               99 |           6
 vac      |               12 |           1
(4 rows)
```

This query provides information on the efficiency of indexes, represented as what percentage of total scans were index scans. A low percentage can indicate under indexing, or wrong data being indexed.

`*link:missing-indexes.sql[missing-indexes]*`
[options="nowrap"]
```
   table_name  | sequential_scans | indexes_scans | diff | table_size |   conclusion
---------------+------------------+---------------+------+------------+----------------
 numbers       |               52 |               |   52 | 8192 bytes | Missing Index?
 vac           |               41 |             6 |   35 | 8192 bytes | Missing Index?
 hot           |                7 |             0 |    7 | 8192 bytes | Missing Index?
 film          |               10 |          1000 | -990 | 440 kB     | OK
 (4 rows)
```

This query displays tables which could be missing and index this is infer based on the number of sequential scans.

`*link:invalid-indexes.sql[invalid-indexes]*`
[options="nowrap"]
```
index_name
------------
(0 rows)
```

This query show any invalid index, an index could be invalid due to an error during its creation, for example when using _CREATE INDEX CONCURRENTLY_. In order to rebuild invalid indexes we have two choices:

* Use the REINDEX command (*not suggested*)
* Drop the index and try to re-build it again (*suggested*)

`*link:cache-hit.sql[cache-hit]*`
[options="nowrap"]
```
       name        | block_read | block_hit |         ratio
-------------------+------------+-----------+------------------------
 Database Hit Rate |       3713 |    508746 | 0.99275454231460468057
 Index Hit Rate    |        543 |    256365 | 0.99788640291466205801
 Table Hit Rate    |        836 |     57765 | 0.98573403184246002628
(3 rows)
```

This query provides information on the efficiency of the buffer cache, for both index reads (index hit rate) as well as table reads (table hit rate). A low buffer cache hit ratio can be a sign that the DB is too small for the workload.

`*link:size-information.sql[size-information]*`
[options="nowrap"]
```
      table       | row_estimate | table_size | index_size | toast_size | total_size
------------------+--------------+------------+------------+------------+------------
 rental           |        16044 | 1224 kB    | 1480 kB    |            | 2704 kB
 payment          |        16049 | 976 kB     | 1200 kB    |            | 2176 kB
 film             |         1000 | 464 kB     | 272 kB     | 8192 bytes | 744 kB
 film_actor       |         5462 | 264 kB     | 312 kB     |            | 576 kB
 inventory        |         4581 | 224 kB     | 280 kB     |            | 504 kB
 customer         |          599 | 96 kB      | 144 kB     |            | 240 kB
 (6 rows)
```

This query displays the total size of each table which include _table size_ + _index size_ + _toast size_.

`*link:db-stats.sql[db-stats]*`
[options="nowrap"]
```
 datname  | commit_ratio | rollback_ratio | deadlocks | conflicts | temp_files | db_size
----------+--------------+----------------+-----------+-----------+------------+---------
 postgres |           99 |              0 |         0 |         0 |          0 | 7071 kB
 workshop |           99 |              0 |         0 |         0 |          0 | 15 MB
(2 rows)
```

This query displays useful stats from our DBs, we want to have a low number of _temp_files_ and no _deadlocks_ or near to zero. One important thing to remember this stats are accumulative so if you want to reset them you need to execute _`SELECT pg_stat_reset();`_

`*link:table-configurations.sql[table-configurations]*`
[options="nowrap"]
```
  table   |         options
----------+--------------------------
 vac      | {autovacuum_enabled=off}
 pg_stats | {security_barrier=true}
(2 rows)
```

This query displays all tables which has some specific configuration. Usually this is useful to check if some table is overriding some specific config which could affect the behaviour of background processes like _AUTOVACUUM_.

`*link:connections.sql[connections]*`
[options="nowrap"]
```
 client_addr | count
-------------+-------
 172.17.0.1  |     3
 172.17.0.2  |     7
(2 rowS)
```

This query displays number of connections per host. This is primarily useful for determining if a specific host is consuming many more connections than expected.

*Note:* This can be a little tricky if multiples instances use the same IP, for example in kubernetes environment several pod could be running in the same node and connecting from the same IP.

`*link:vacuum-stats.sql[vacuum-stats]*`
[options="nowrap"]
```
      table       | last_vacuum | last_autovacuum |    rowcount    | dead_rowcount  | autovacuum_threshold | expect_autovacuum
------------------+-------------+-----------------+----------------+----------------+----------------------+-------------------
 example          |             |                 |            200 |              0 |             90       |
(1 row)
```

This query displays statistics related to vacuum operations for each table, including an estiamtion of dead rows, last autovacuum and the current autovacuum threshold. It can be useful when determining if current vacuum thresholds require adjustments, and to determine when the table was last vacuumed.

`*link:vacuum-execution.sql[vacuum-execution]*`
[options="nowrap"]
```
 datname  | usename  | pid |  state  | wait_event |       xact_runtime      |                       query
----------+----------+-----+-------+------------+--------------+-------------------------------------------------------------------------
 workshop | postgres |  66 | active  |            | 33 days 16:32:11.600656 | autovacuum: VACUUM ANALYZE customer (to prevent wraparound)
 workshop | postgres |  68 | active  |            | 14 days 09:15:34.073141 | autovacuum: VACUUM ANALYZE category (to prevent wraparound)
 workshop | postgres |  70 | active  |            | 3 days 02:43:54.203349  | autovacuum: VACUUM ANALYZE film
(3 rows)
```

This query displays if any _VACUUM_ task is running and how long has been running.

`*link:bloat.sql[bloat]*`
[options="nowrap"]
```
 type  | schemaname |                         object_name                         | bloat |   waste
-------+------------+-------------------------------------------------------------+-------+------------
 table | public     | rental                                                      |   1.2 | 184 kB
 index | public     | film_actor::idx_fk_film_id                                  |   1.3 | 40 kB
 index | public     | inventory::idx_store_id_film_id                             |   1.3 | 32 kB
 table | public     | film_actor                                                  |   1.1 | 24 kB
 (4 rows)
```

This query displays an estimation of table "bloat" – space allocated to a relation that is full of dead tuples, that has yet to be reclaimed. Tables that have a high bloat ratio, typically 10 or greater, should be investigated to see if vacuuming is aggressive enough, and can be a sign of high table churn.